# Generated by Django 2.2.9 on 2023-01-31 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230131_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
